on:
  pull_request:
    branches:
      - feature/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if java-11 is already cached
        uses: actions/cache@v2
        id: cache-java
        with:
          path: ~/.cache/java-11
          key: java-11
    
      - name: Install Java-11
        if: steps.cache-java.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -q
          sudo apt-get install -y openjdk-11-jdk

      - name: Checking Java Version
        run: java -version
