
name: Caching java

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/test
          key: java-11
    
      - name: Install Java-11
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -q
          sudo apt-get install -y openjdk-11-jdk

      - name: Checking Java Version
        run: java -version
