
name: Caching java

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    # install java-11 if not cached already
      - uses: actions/cache@v2
        id: cache-java
        with:
          path: ~/.cache/java-11
          key: java-11
    
      - name: Install Java-11
        if: steps.cache-java.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -q
          sudo apt-get install -y openjdk-11-jdk

      - name: Checking Java Version
        run: java -version

    # install maven if not cached already
      - uses: actions/cache@v2
        id: cache-maven
        with:
          path: ~/.cache/maven
          key: maven
    
      - name: Install Maven
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y maven

      - name: Checking Maven Version
        run: mvn -version

    # install docker if not cached already
      - uses: actions/cache@v2
        id: cache-docker
        with:
          path: ~/.cache/docker
          key: maven
    
      - name: Install docker
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          sudo apt install apt-transport
          curl -fsSL ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64]
          sudo apt-get remove docker docker-engine docker.io
          sudo apt-get update
          sudo apt install docker.io
          sudo snap install docker
          
      - name: Checking Docker Version
        run: sudo docker -version
