
name: Caching java

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # # install java-11 if not cached already
      # - name: Check if java-11 is already cached
      #   uses: actions/cache@v2
      #   id: cache-java
      #   with:
      #     path: ~/.cache/java-11
      #     key: java-11
    
      # - name: Install Java-11
      #   if: steps.cache-java.outputs.cache-hit != 'true'
      #   run: |
      #     sudo apt-get update -q
      #     sudo apt-get install -y openjdk-11-jdk

      # - name: Checking Java Version
      #   run: java -version

      # Include another YAML file
      - name: Include sub-workflow
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
          path: .github/workflows/java-install.yml

      # install maven if not cached already
      - name: Check if maven is already cached
        uses: actions/cache@v2
        id: cache-maven
        with:
          path: ~/.cache/maven
          key: maven
    
      - name: Install Maven
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y maven

      - name: Checking Maven Version
        run: mvn -version

      # install docker
      - name: Check if Docker is cached
        id: cache-docker
        uses: actions/cache@v2
        with:
          path:  ~/.cache/docker
          key: docker-${{ runner.os }}
  
      - name: Install Docker
        if: steps.cache-docker.outputs.cache-hit != 'true'
        uses: docker-practice/actions-setup-docker@master
  
      - name: Checking Docker Version
        run: sudo docker --version

    # install aws localstack
      - name: Check if aws localstack is cached
        id: cache-aws-localstack
        uses: actions/cache@v2
        with:
          path:  ~/.cache/aws-localstack
          key: localstack

      - name: Run an user define shell script
        run: |
          script_path="${GITHUB_WORKSPACE}/start.sh"
          chmod +x script.sh
          ./script.sh

          
      # - name: run localstack
      #   run: |
      #     #!/bin/bash
      #     # Set environment variables if needed
      #     export LOCALSTACK_DOCKER_NAME="test";
      #     export PORT_WEB_UI=${PORT_WEB_UI-8060}
          
      #     # Run LocalStack container
      #     docker run -d \
      #         --name $LOCALSTACK_DOCKER_NAME \
      #         -p 4566-4599:4566-4599 \
      #         -p $PORT_WEB_UI:$PORT_WEB_UI \
      #         localstack/localstack:0.12.6

      - name: Check if localstack is running or not
        run: docker ps
