name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.test
          key: ${{ runner.os }}-"test" }}
    
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "hello there"
