name: Super_Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Java 11
        uses: actions/cache@v2
        with:
          path: ~/.cache/openjdk11
          key: java11-${{ runner.os }}

      - name: Set up Java 11
        run: |
          # Check if Java 11 is already cached; if not, install it
          if [ ! -d ~/.cache/openjdk11 ]; then
            sudo apt-get update -q
            sudo apt-get install -y openjdk-11-jdk
          fi
