name: Super_Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Java 11
        uses: actions/cache@v2
        with:
          cache: java11
          run: |
            sudo apt-get update -q
            sudo apt-get install -y openjdk-11-jdk
            
