
name: Caching java

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # install java-11 if not cached already
      - name: Check if java-11 is already cached
        uses: actions/cache@v2
        id: cache-java
        with:
          path: ~/.cache/java-11
          key: java-11
    
      - name: Install Java-11
        if: steps.cache-java.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -q
          sudo apt-get install -y openjdk-11-jdk

      - name: Checking Java Version
        run: java -version

      # install maven if not cached already
      - name: Check if maven is already cached
        uses: actions/cache@v2
        id: cache-maven
        with:
          path: ~/.cache/maven
          key: maven
    
      - name: Install Maven
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y maven

      - name: Checking Maven Version
        run: mvn -version

      # install docker
      - name: Check if Docker is cached
        id: cache-docker
        uses: actions/cache@v2
        with:
          path:  ~/.cache/docker
          key: docker-${{ runner.os }}
  
      - name: Install Docker
        if: steps.cache-docker.outputs.cache-hit != 'true'
        uses: docker-practice/actions-setup-docker@master
  
      - name: Checking Docker Version
        run: sudo docker --version

    # install aws localstack
      - name: Check if aws localstack is cached
        id: cache-aws-localstack
        uses: actions/cache@v2
        with:
          path:  ~/.cache/aws-localstack
          key: localstack
          
      - name: Start LocalStack
        if: steps.cache-aws-localstack.outputs.cache-hit != 'true'
        run: |
            pip install localstack awscli-local[ver1] # install LocalStack cli and awslocal

      - name: Run some Tests against LocalStack
        run: |
            docker pull localstack/localstack         # Make sure to pull the latest version of the image
            localstack start -d                       # Start LocalStack in the background
            echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
            localstack wait -t 30                     # to become ready before timing out 
            echo "Startup complete"
            
            awslocal s3 mb s3://test
            awslocal s3 ls
            echo "Test Execution complete!"   
