
name: Caching java

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Include another YAML file
      - name: Include sub-workflow
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
          path: |
            .github/workflows/java-install.yml
            .github/workflows/maven.yml

      # install docker
      - name: Check if Docker is cached
        id: cache-docker
        uses: actions/cache@v2
        with:
          path:  ~/.cache/docker
          key: docker-${{ runner.os }}
  
      - name: Install Docker
        if: steps.cache-docker.outputs.cache-hit != 'true'
        uses: docker-practice/actions-setup-docker@master
  
      - name: Checking Docker Version
        run: sudo docker --version

    # install aws localstack
      - name: Check if aws localstack is cached
        id: cache-aws-localstack
        uses: actions/cache@v2
        with:
          path:  ~/.cache/aws-localstack
          key: localstack

      - name: Run an user define shell script
        run: |
          script_path="${GITHUB_WORKSPACE}/start.sh"
          chmod +x script.sh
          ./script.sh

          
      # - name: run localstack
      #   run: |
      #     #!/bin/bash
      #     # Set environment variables if needed
      #     export LOCALSTACK_DOCKER_NAME="test";
      #     export PORT_WEB_UI=${PORT_WEB_UI-8060}
          
      #     # Run LocalStack container
      #     docker run -d \
      #         --name $LOCALSTACK_DOCKER_NAME \
      #         -p 4566-4599:4566-4599 \
      #         -p $PORT_WEB_UI:$PORT_WEB_UI \
      #         localstack/localstack:0.12.6

      - name: Check if localstack is running or not
        run: docker ps
