name: Super_Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 11
        run: |
          sudo apt-get update -q
          sudo apt-get install -y openjdk-11-jdk
          java -version

      - name: Run an user define shell script
        run: |
          script_path="${GITHUB_WORKSPACE}/script.sh"
          chmod +x script.sh
          ./script.sh

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
