
name: Caching java

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    # install java-11 if not cached already
      - uses: actions/cache@v2
        id: cache-java
        with:
          path: ~/.cache/java-11
          key: java-11
    
      - name: Install Java-11
        if: steps.cache-java.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -q
          sudo apt-get install -y openjdk-11-jdk

      - name: Checking Java Version
        run: java -version

    # install maven if not cached already
      - uses: actions/cache@v2
        id: cache-maven
        with:
          path: ~/.cache/maven
          key: maven
    
      - name: Install Maven
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y maven

      - name: Checking Maven Version
        run: mvn -version

    # install docker if not cached already
      - uses: actions/cache@v2
        id: cache-docker
        with:
          path: ~/.cache/docker
          key: maven
    
      - name: Install docker
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          sudo apt-get install docker-ce dock ber-ce-cli containerd.io docker-compose-plugin
          apt-cache madison docker-ce | awk '{ print $3 }'
          VERSION_STRING=5:20.10.13~3-0~ubuntu-jammy
          sudo apt-get install docker-ce=$VERSION_STRING docker-ce-cli=$VERSION_STRING containerd.io docker-compose-plugin

          
      - name: Checking Docker Version
        run: sudo docker -version
